// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubstanciasDatabase;

#nullable disable

namespace SubstanciasDatabase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubstanciasLibrary.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("propriedades", (string)null);
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.Substancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("substancias", (string)null);
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.SubstanciaPropriedade", b =>
                {
                    b.Property<int>("SubstanciaId")
                        .HasColumnType("integer");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("SubstanciaId", "PropriedadeId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("substancia_propriedades", (string)null);
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.Substancia", b =>
                {
                    b.HasOne("SubstanciasLibrary.Models.Categoria", "Categoria")
                        .WithMany("Substancias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.SubstanciaPropriedade", b =>
                {
                    b.HasOne("SubstanciasLibrary.Models.Propriedade", "Propriedade")
                        .WithMany("SubstanciaPropriedades")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubstanciasLibrary.Models.Substancia", "Substancia")
                        .WithMany("SubstanciaPropriedades")
                        .HasForeignKey("SubstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");

                    b.Navigation("Substancia");
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.Categoria", b =>
                {
                    b.Navigation("Substancias");
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.Propriedade", b =>
                {
                    b.Navigation("SubstanciaPropriedades");
                });

            modelBuilder.Entity("SubstanciasLibrary.Models.Substancia", b =>
                {
                    b.Navigation("SubstanciaPropriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
